### ISSUE TITLE
pyhelm library errors with grpc_status:14

### ISSUE THREAD

**Issue by javierdompablo** [ansible-collections/community.kubernetes#144]
##### SUMMARY
Errors in the `pyhelm` library with status code 14 when deployment a public chart.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
helm module

##### ANSIBLE VERSION
```paste below
ansible 2.9.9
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_PIPELINING(env: ANSIBLE_PIPELINING) = True
ANSIBLE_SSH_ARGS(env: ANSIBLE_SSH_ARGS) = -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r  -o PreferredAuthentications=publickey -o ForwardAgent=yes -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o StrictHostKeyChecking=no -q
CACHE_PLUGIN(env: ANSIBLE_CACHE_PLUGIN) = jsonfile
CACHE_PLUGIN_CONNECTION(env: ANSIBLE_CACHE_PLUGIN_CONNECTION) = .ansible
CACHE_PLUGIN_TIMEOUT(env: ANSIBLE_CACHE_PLUGIN_TIMEOUT) = 86400
DEFAULT_FORKS(env: ANSIBLE_FORKS) = 200
DEFAULT_GATHER_TIMEOUT(env: ANSIBLE_GATHER_TIMEOUT) = 30
DEFAULT_HASH_BEHAVIOUR(env: ANSIBLE_HASH_BEHAVIOUR) = merge
DEFAULT_REMOTE_USER(env: ANSIBLE_REMOTE_USER) = ec2-user
DEFAULT_SCP_IF_SSH(env: ANSIBLE_SCP_IF_SSH) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = yaml
DEFAULT_TIMEOUT(env: ANSIBLE_TIMEOUT) = 30
DEPRECATION_WARNINGS(env: ANSIBLE_DEPRECATION_WARNINGS) = False
DISPLAY_SKIPPED_HOSTS(env: DISPLAY_SKIPPED_HOSTS) = False
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False
```

##### OS / ENVIRONMENT
MacOSX
##### STEPS TO REPRODUCE

```yaml
- name: Example helm
  hosts: localhost
  tags: always
  gather_facts: false
  tasks:
    - name: Install helm chart from a git repo specifying path
      helm:
        host: localhost
        chart:
          name: memcached
          source:
            type: git
            location: https://github.com/helm/charts.git
            path: stable/memcached
        state: present
        name: my-memcached
        namespace: default
```

##### EXPECTED RESULTS
Deploy the chart in local

##### ACTUAL RESULTS
```shell
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    2020-06-25 18:14:11,798 - ChartBuilder - INFO - Cloning https://github.com/helm/charts.git/ for release memcached
    Traceback (most recent call last):
      File "<stdin>", line 102, in <module>
      File "<stdin>", line 94, in _ansiballz_main
      File "<stdin>", line 40, in invoke_module
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/var/folders/z9/nhrcvwtd3lb8d73w74_p_w240000gq/T/ansible_helm_payload_4j8w5wzx/ansible_helm_payload.zip/ansible/modules/cloud/misc/helm.py", line 207, in <module>
      File "/var/folders/z9/nhrcvwtd3lb8d73w74_p_w240000gq/T/ansible_helm_payload_4j8w5wzx/ansible_helm_payload.zip/ansible/modules/cloud/misc/helm.py", line 195, in main
      File "/var/folders/z9/nhrcvwtd3lb8d73w74_p_w240000gq/T/ansible_helm_payload_4j8w5wzx/ansible_helm_payload.zip/ansible/modules/cloud/misc/helm.py", line 127, in install
      File "/Library/Python/3.7/site-packages/pyhelm/tiller.py", line 114, in list_releases
        for y in release_list:
      File "/Library/Python/3.7/site-packages/grpc/_channel.py", line 416, in __next__
        return self._next()
      File "/Library/Python/3.7/site-packages/grpc/_channel.py", line 706, in _next
        raise self
    grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
            status = StatusCode.UNAVAILABLE
            details = "failed to connect to all addresses"
            debug_error_string = "{"created":"@1593101663.663713000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3981,"referenced_errors":[{"created":"@1593101663.663711000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
    >
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by geerlingguy** [comment]
@javierdompablo - It looks like you're hitting errors with the helm module that ships with Ansible core in 2.9 and earlier. That module was deprecated and is no longer maintained. The version of the `helm` module in this collection is made to work with Helm 3 and later, and is actively maintained.

I would recommend moving off of the older helm module and using this one instead.

(Please correct me if wrong—but I am going to close this issue as it can't be fixed by anything in this repository.)
