### ISSUE TITLE
K8s_info module: error when using variable as app label selector

### ISSUE THREAD

**Issue by ElioLopez-md** [ansible-collections/community.kubernetes#151]
##### SUMMARY
The k8s_info module fails when using a variable as label selector.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = None
  configured module search path = ['/Users/elopez/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, May 27 2020, 20:54:22) [Clang 11.0.3 (clang-1103.0.32.59)]
```

##### CONFIGURATION

```paste below
ACTION_WARNINGS(default) = True
AGNOSTIC_BECOME_PROMPT(default) = True
ALLOW_WORLD_READABLE_TMPFILES(default) = False
ANSIBLE_CONNECTION_PATH(default) = None
ANSIBLE_COW_PATH(default) = None
ANSIBLE_COW_SELECTION(default) = default
ANSIBLE_COW_WHITELIST(default) = ['bud-frogs', 'bunny', 'cheese', 'daemon', 'default', 'dragon', 'elephant-in-snake', 'elephant', 'eyes', 'hellokitty', 'kitty', 'luke-koala', 'meow', 'milk', 'moofasa', 'moose', 'ren', 'sheep', 'small', 'stegosaurus', 'stimpy', 'supermilker', 'three-eyes', 'turkey', 'turtle', 'tux', 'udder', 'vader-koala', 'vader', 'www']
ANSIBLE_FORCE_COLOR(default) = False
ANSIBLE_NOCOLOR(default) = False
ANSIBLE_NOCOWS(default) = False
ANSIBLE_PIPELINING(default) = False
ANSIBLE_SSH_ARGS(default) = -C -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(default) = None
ANSIBLE_SSH_CONTROL_PATH_DIR(default) = ~/.ansible/cp
ANSIBLE_SSH_EXECUTABLE(default) = ssh
ANSIBLE_SSH_RETRIES(default) = 0
ANY_ERRORS_FATAL(default) = False
BECOME_ALLOW_SAME_USER(default) = False
BECOME_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/become', '/usr/share/ansible/plugins/become']
CACHE_PLUGIN(default) = memory
CACHE_PLUGIN_CONNECTION(default) = None
CACHE_PLUGIN_PREFIX(default) = ansible_facts
CACHE_PLUGIN_TIMEOUT(default) = 86400
COLLECTIONS_PATHS(default) = ['/Users/elopez/.ansible/collections', '/usr/share/ansible/collections']
COLOR_CHANGED(default) = yellow
COLOR_CONSOLE_PROMPT(default) = white
COLOR_DEBUG(default) = dark gray
COLOR_DEPRECATE(default) = purple
COLOR_DIFF_ADD(default) = green
COLOR_DIFF_LINES(default) = cyan
COLOR_DIFF_REMOVE(default) = red
COLOR_ERROR(default) = red
COLOR_HIGHLIGHT(default) = white
COLOR_OK(default) = green
COLOR_SKIP(default) = cyan
COLOR_UNREACHABLE(default) = bright red
COLOR_VERBOSE(default) = blue
COLOR_WARN(default) = bright purple
COMMAND_WARNINGS(default) = True
CONDITIONAL_BARE_VARS(default) = True
CONNECTION_FACTS_MODULES(default) = {'eos': 'eos_facts', 'frr': 'frr_facts', 'ios': 'ios_facts', 'iosxr': 'iosxr_facts', 'junos': 'junos_facts', 'nxos': 'nxos_facts', 'vyos': 'vyos_facts'}
COVERAGE_REMOTE_OUTPUT(default) = None
COVERAGE_REMOTE_WHITELIST(default) = *
DEFAULT_ACTION_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/action', '/usr/share/ansible/plugins/action']
DEFAULT_ALLOW_UNSAFE_LOOKUPS(default) = False
DEFAULT_ASK_PASS(default) = False
DEFAULT_ASK_VAULT_PASS(default) = False
DEFAULT_BECOME(default) = False
DEFAULT_BECOME_ASK_PASS(default) = False
DEFAULT_BECOME_EXE(default) = None
DEFAULT_BECOME_FLAGS(default) = 
DEFAULT_BECOME_METHOD(default) = sudo
DEFAULT_BECOME_USER(default) = root
DEFAULT_CACHE_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/cache', '/usr/share/ansible/plugins/cache']
DEFAULT_CALLABLE_WHITELIST(default) = []
DEFAULT_CALLBACK_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/callback', '/usr/share/ansible/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(default) = []
DEFAULT_CLICONF_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/cliconf', '/usr/share/ansible/plugins/cliconf']
DEFAULT_CONNECTION_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/connection', '/usr/share/ansible/plugins/connection']
DEFAULT_DEBUG(default) = False
DEFAULT_EXECUTABLE(default) = /bin/sh
DEFAULT_FACT_PATH(default) = None
DEFAULT_FILTER_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/filter', '/usr/share/ansible/plugins/filter']
DEFAULT_FORCE_HANDLERS(default) = False
DEFAULT_FORKS(default) = 5
DEFAULT_GATHERING(default) = implicit
DEFAULT_GATHER_SUBSET(default) = ['all']
DEFAULT_GATHER_TIMEOUT(default) = 10
DEFAULT_HANDLER_INCLUDES_STATIC(default) = False
DEFAULT_HASH_BEHAVIOUR(default) = replace
DEFAULT_HOST_LIST(default) = ['/etc/ansible/hosts']
DEFAULT_HTTPAPI_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/httpapi', '/usr/share/ansible/plugins/httpapi']
DEFAULT_INTERNAL_POLL_INTERVAL(default) = 0.001
DEFAULT_INVENTORY_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/inventory', '/usr/share/ansible/plugins/inventory']
DEFAULT_JINJA2_EXTENSIONS(default) = []
DEFAULT_JINJA2_NATIVE(default) = False
DEFAULT_KEEP_REMOTE_FILES(default) = False
DEFAULT_LIBVIRT_LXC_NOSECLABEL(default) = False
DEFAULT_LOAD_CALLBACK_PLUGINS(default) = False
DEFAULT_LOCAL_TMP(default) = /Users/elopez/.ansible/tmp/ansible-local-43072f884f35v
DEFAULT_LOG_FILTER(default) = []
DEFAULT_LOG_PATH(default) = None
DEFAULT_LOOKUP_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/lookup', '/usr/share/ansible/plugins/lookup']
DEFAULT_MANAGED_STR(default) = Ansible managed
DEFAULT_MODULE_ARGS(default) = 
DEFAULT_MODULE_COMPRESSION(default) = ZIP_DEFLATED
DEFAULT_MODULE_NAME(default) = command
DEFAULT_MODULE_PATH(default) = ['/Users/elopez/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
DEFAULT_MODULE_UTILS_PATH(default) = ['/Users/elopez/.ansible/plugins/module_utils', '/usr/share/ansible/plugins/module_utils']
DEFAULT_NETCONF_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/netconf', '/usr/share/ansible/plugins/netconf']
DEFAULT_NO_LOG(default) = False
DEFAULT_NO_TARGET_SYSLOG(default) = False
DEFAULT_NULL_REPRESENTATION(default) = None
DEFAULT_POLL_INTERVAL(default) = 15
DEFAULT_PRIVATE_KEY_FILE(default) = None
DEFAULT_PRIVATE_ROLE_VARS(default) = False
DEFAULT_REMOTE_PORT(default) = None
DEFAULT_REMOTE_USER(default) = None
DEFAULT_ROLES_PATH(default) = ['/Users/elopez/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles']
DEFAULT_SCP_IF_SSH(default) = smart
DEFAULT_SELINUX_SPECIAL_FS(default) = ['fuse', 'nfs', 'vboxsf', 'ramfs', '9p', 'vfat']
DEFAULT_SFTP_BATCH_MODE(default) = True
DEFAULT_SQUASH_ACTIONS(default) = ['apk', 'apt', 'dnf', 'homebrew', 'openbsd_pkg', 'pacman', 'pip', 'pkgng', 'yum', 'zypper']
DEFAULT_SSH_TRANSFER_METHOD(default) = None
DEFAULT_STDOUT_CALLBACK(default) = default
DEFAULT_STRATEGY(default) = linear
DEFAULT_STRATEGY_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/strategy', '/usr/share/ansible/plugins/strategy']
DEFAULT_SU(default) = False
DEFAULT_SYSLOG_FACILITY(default) = LOG_USER
DEFAULT_TASK_INCLUDES_STATIC(default) = False
DEFAULT_TERMINAL_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/terminal', '/usr/share/ansible/plugins/terminal']
DEFAULT_TEST_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/test', '/usr/share/ansible/plugins/test']
DEFAULT_TIMEOUT(default) = 10
DEFAULT_TRANSPORT(default) = smart
DEFAULT_UNDEFINED_VAR_BEHAVIOR(default) = True
DEFAULT_VARS_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/vars', '/usr/share/ansible/plugins/vars']
DEFAULT_VAULT_ENCRYPT_IDENTITY(default) = None
DEFAULT_VAULT_IDENTITY(default) = default
DEFAULT_VAULT_IDENTITY_LIST(default) = []
DEFAULT_VAULT_ID_MATCH(default) = False
DEFAULT_VAULT_PASSWORD_FILE(default) = None
DEFAULT_VERBOSITY(default) = 0
DEPRECATION_WARNINGS(default) = True
DIFF_ALWAYS(default) = False
DIFF_CONTEXT(default) = 3
DISPLAY_ARGS_TO_STDOUT(default) = False
DISPLAY_SKIPPED_HOSTS(default) = True
DOCSITE_ROOT_URL(default) = https://docs.ansible.com/ansible/
DOC_FRAGMENT_PLUGIN_PATH(default) = ['/Users/elopez/.ansible/plugins/doc_fragments', '/usr/share/ansible/plugins/doc_fragments']
DUPLICATE_YAML_DICT_KEY(default) = warn
ENABLE_TASK_DEBUGGER(default) = False
ERROR_ON_MISSING_HANDLER(default) = True
FACTS_MODULES(default) = ['smart']
GALAXY_IGNORE_CERTS(default) = False
GALAXY_ROLE_SKELETON(default) = None
GALAXY_ROLE_SKELETON_IGNORE(default) = ['^.git$', '^.*/.git_keep$']
GALAXY_SERVER(default) = https://galaxy.ansible.com
GALAXY_SERVER_LIST(default) = None
GALAXY_TOKEN(default) = None
GALAXY_TOKEN_PATH(default) = /Users/elopez/.ansible/galaxy_token
HOST_KEY_CHECKING(default) = True
HOST_PATTERN_MISMATCH(default) = warning
INJECT_FACTS_AS_VARS(default) = True
INTERPRETER_PYTHON(default) = auto_legacy
INTERPRETER_PYTHON_DISTRO_MAP(default) = {'centos': {'6': '/usr/bin/python', '8': '/usr/libexec/platform-python'}, 'fedora': {'23': '/usr/bin/python3'}, 'redhat': {'6': '/usr/bin/python', '8': '/usr/libexec/platform-python'}, 'rhel': {'6': '/usr/bin/python', '8': '/usr/libexec/platform-python'}, 'ubuntu': {'14': '/usr/bin/python', '16': '/usr/bin/python3'}}
INTERPRETER_PYTHON_FALLBACK(default) = ['/usr/bin/python', 'python3.7', 'python3.6', 'python3.5', 'python2.7', 'python2.6', '/usr/libexec/platform-python', '/usr/bin/python3', 'python']
INVALID_TASK_ATTRIBUTE_FAILED(default) = True
INVENTORY_ANY_UNPARSED_IS_FAILED(default) = False
INVENTORY_CACHE_ENABLED(default) = False
INVENTORY_CACHE_PLUGIN(default) = None
INVENTORY_CACHE_PLUGIN_CONNECTION(default) = None
INVENTORY_CACHE_PLUGIN_PREFIX(default) = ansible_facts
INVENTORY_CACHE_TIMEOUT(default) = 3600
INVENTORY_ENABLED(default) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml']
INVENTORY_EXPORT(default) = False
INVENTORY_IGNORE_EXTS(default) = {{(BLACKLIST_EXTS + ( '.orig', '.ini', '.cfg', '.retry'))}}
INVENTORY_IGNORE_PATTERNS(default) = []
INVENTORY_UNPARSED_IS_FAILED(default) = False
LOCALHOST_WARNING(default) = True
MAX_FILE_SIZE_FOR_DIFF(default) = 104448
NETCONF_SSH_CONFIG(default) = None
NETWORK_GROUP_MODULES(default) = ['eos', 'nxos', 'ios', 'iosxr', 'junos', 'enos', 'ce', 'vyos', 'sros', 'dellos9', 'dellos10', 'dellos6', 'asa', 'aruba', 'aireos', 'bigip', 'ironware', 'onyx', 'netconf']
OLD_PLUGIN_CACHE_CLEARING(default) = False
PARAMIKO_HOST_KEY_AUTO_ADD(default) = False
PARAMIKO_LOOK_FOR_KEYS(default) = True
PERSISTENT_COMMAND_TIMEOUT(default) = 30
PERSISTENT_CONNECT_RETRY_TIMEOUT(default) = 15
PERSISTENT_CONNECT_TIMEOUT(default) = 30
PERSISTENT_CONTROL_PATH_DIR(default) = /Users/elopez/.ansible/pc
PLAYBOOK_DIR(default) = None
PLAYBOOK_VARS_ROOT(default) = top
PLUGIN_FILTERS_CFG(default) = None
PYTHON_MODULE_RLIMIT_NOFILE(default) = 0
RETRY_FILES_ENABLED(default) = False
RETRY_FILES_SAVE_PATH(default) = None
SHOW_CUSTOM_STATS(default) = False
STRING_CONVERSION_ACTION(default) = warn
STRING_TYPE_FILTERS(default) = ['string', 'to_json', 'to_nice_json', 'to_yaml', 'ppretty', 'json']
SYSTEM_WARNINGS(default) = True
TAGS_RUN(default) = []
TAGS_SKIP(default) = []
TASK_DEBUGGER_IGNORE_ERRORS(default) = True
TRANSFORM_INVALID_GROUP_CHARS(default) = never
USE_PERSISTENT_CONNECTIONS(default) = False
VARIABLE_PRECEDENCE(default) = ['all_inventory', 'groups_inventory', 'all_plugins_inventory', 'all_plugins_play', 'groups_plugins_inventory', 'groups_plugins_play']
VERBOSE_TO_STDERR(default) = False
YAML_FILENAME_EXTENSIONS(default) = ['.yml', '.yaml', '.json']

```

##### OS / ENVIRONMENT
macOS Catalina, but also failed on Debian buster Docker Image

##### STEPS TO REPRODUCE

Im using the following directory structure:
```yaml
elopez@MacBook-Pro error_when_using_variable % tree 
.
├── inventories
│   └── test
│       ├── group_vars
│       │   └── all.yml
│       └── hosts.ini
├── k8s_verify_error.yml
├── k8s_verify_ok.yml
```
with the following file contents:
```yaml
elopez@MacBook-Pro error_when_using_variable % cat inventories/test/hosts.ini 
localhost0 ansible_connection=local
```

```yaml
elopez@MacBook-Pro error_when_using_variable % cat inventories/test/group_vars/all.yml
namespace: developer-portal
application: developer-portal-backend
```

```yaml
elopez@MacBook-Pro error_when_using_variable % cat k8s_verify_ok.yml             
---
- hosts: all
  gather_facts: false
  collections:
    - community.kubernetes

  tasks:
    - name: Get a list of all pods from "{{ application }}" app on "{{ namespace }}" namespace
      k8s_info:
        kind: Pod
        namespace: "{{ namespace }}"
        label_selectors:
              - app = developer-portal-backend
      register: pod_list
```

```yaml
elopez@MacBook-Pro error_when_using_variable % cat k8s_verify_error.yml             
---
- hosts: all
  gather_facts: false
  collections:
    - community.kubernetes

  tasks:
    - name: Get a list of all pods from "{{ application }}" app on "{{ namespace }}" namespace
      k8s_info:
        kind: Pod
        namespace: "{{ namespace }}"
        label_selectors:
              - app =  "{{ application }}"
      register: pod_list
```

this is working properly:
```yaml
elopez@MacBook-Pro error_when_using_variable % ansible-playbook -i inventories/test/hosts.ini k8s_verify_ok.yml   

PLAY [all] **************************************************************************************************************************************************************

TASK [Get a list of all pods from "developer-portal-backend" app on "developer-portal" namespace] ***********************************************************************
[WARNING]: Platform darwin on host localhost0 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could
change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
ok: [localhost0]

TASK [debug] ************************************************************************************************************************************************************
ok: [localhost0] => {
    "namespace": "developer-portal"
}

TASK [debug] ************************************************************************************************************************************************************
ok: [localhost0] => {
    "application": "developer-portal-backend"
}

PLAY RECAP **************************************************************************************************************************************************************
localhost0                 : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

elopez@MacBook-Pro error_when_using_variable % 
```

this is not:
```yaml
elopez@MacBook-Pro error_when_using_variable % ansible-playbook -i inventories/test/hosts.ini k8s_verify_error.yml -vvv
ansible-playbook 2.9.6
  config file = None
  configured module search path = ['/Users/elopez/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.6_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.3 (default, May 27 2020, 20:54:22) [Clang 11.0.3 (clang-1103.0.32.59)]
No config file found; using defaults
host_list declined parsing /Users/elopez/repos/K8s_Ansible_test/error_when_using_variable/inventories/test/hosts.ini as it did not pass its verify_file() method
script declined parsing /Users/elopez/repos/K8s_Ansible_test/error_when_using_variable/inventories/test/hosts.ini as it did not pass its verify_file() method
auto declined parsing /Users/elopez/repos/K8s_Ansible_test/error_when_using_variable/inventories/test/hosts.ini as it did not pass its verify_file() method
yaml declined parsing /Users/elopez/repos/K8s_Ansible_test/error_when_using_variable/inventories/test/hosts.ini as it did not pass its verify_file() method
Parsed /Users/elopez/repos/K8s_Ansible_test/error_when_using_variable/inventories/test/hosts.ini inventory source with ini plugin

PLAYBOOK: k8s_verify_error.yml ******************************************************************************************************************************************
1 plays in k8s_verify_error.yml

PLAY [all] **************************************************************************************************************************************************************
META: ran handlers

TASK [Get a list of all pods from "developer-portal-backend" app on "developer-portal" namespace] ***********************************************************************
task path: /Users/elopez/repos/K8s_Ansible_test/error_when_using_variable/k8s_verify_error.yml:9
<localhost0> ESTABLISH LOCAL CONNECTION FOR USER: elopez
<localhost0> EXEC /bin/sh -c 'echo ~elopez && sleep 0'
<localhost0> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157 `" && echo ansible-tmp-1593779716.8926852-80440910949157="` echo /Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157 `" ) && sleep 0'
<localhost0> Attempting python interpreter discovery
<localhost0> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost0> Python interpreter discovery fallback (unsupported platform for extended discovery: darwin)
Using module file /Users/elopez/.ansible/collections/ansible_collections/community/kubernetes/plugins/modules/k8s_info.py
<localhost0> PUT /Users/elopez/.ansible/tmp/ansible-local-430244frywny1/tmpqy4ctjh7 TO /Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/AnsiballZ_k8s_info.py
<localhost0> EXEC /bin/sh -c 'chmod u+x /Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/ /Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/AnsiballZ_k8s_info.py && sleep 0'
<localhost0> EXEC /bin/sh -c '/usr/bin/python /Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/AnsiballZ_k8s_info.py && sleep 0'
<localhost0> EXEC /bin/sh -c 'rm -f -r /Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/AnsiballZ_k8s_info.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/AnsiballZ_k8s_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/AnsiballZ_k8s_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.kubernetes.plugins.modules.k8s_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/folders/l3/q6bmclbd53360skfvrqfcbr00000gp/T/ansible_k8s_info_payload_bGc4GK/ansible_k8s_info_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s_info.py", line 185, in <module>
  File "/var/folders/l3/q6bmclbd53360skfvrqfcbr00000gp/T/ansible_k8s_info_payload_bGc4GK/ansible_k8s_info_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s_info.py", line 181, in main
  File "/var/folders/l3/q6bmclbd53360skfvrqfcbr00000gp/T/ansible_k8s_info_payload_bGc4GK/ansible_k8s_info_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s_info.py", line 162, in execute_module
  File "/var/folders/l3/q6bmclbd53360skfvrqfcbr00000gp/T/ansible_k8s_info_payload_bGc4GK/ansible_k8s_info_payload.zip/ansible_collections/community/kubernetes/plugins/module_utils/common.py", line 229, in kubernetes_facts
  File "/Users/elopez/Library/Python/2.7/lib/python/site-packages/openshift/dynamic/client.py", line 94, in get
    return self.request('get', path, **kwargs)
  File "/Users/elopez/Library/Python/2.7/lib/python/site-packages/openshift/dynamic/client.py", line 44, in inner
    raise api_exception(e)
openshift.dynamic.exceptions.BadRequestError: 400
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 03 Jul 2020 12:35:19 GMT', 'Content-Length': '489', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"unable to parse requirement: invalid label value: \"\\\"developer-portal-backend\\\"\": at key: \"app\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')","reason":"BadRequest","code":400}

Original traceback: 
  File "/Users/elopez/Library/Python/2.7/lib/python/site-packages/openshift/dynamic/client.py", line 42, in inner
    resp = func(self, *args, **kwargs)

  File "/Users/elopez/Library/Python/2.7/lib/python/site-packages/openshift/dynamic/client.py", line 247, in request
    _return_http_data_only=params.get('_return_http_data_only', True)

  File "/Users/elopez/Library/Python/2.7/lib/python/site-packages/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)

  File "/Users/elopez/Library/Python/2.7/lib/python/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)

  File "/Users/elopez/Library/Python/2.7/lib/python/site-packages/kubernetes/client/api_client.py", line 366, in request
    headers=headers)

  File "/Users/elopez/Library/Python/2.7/lib/python/site-packages/kubernetes/client/rest.py", line 241, in GET
    query_params=query_params)

  File "/Users/elopez/Library/Python/2.7/lib/python/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)

[WARNING]: Platform darwin on host localhost0 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could
change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
fatal: [localhost0]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/AnsiballZ_k8s_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/AnsiballZ_k8s_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/elopez/.ansible/tmp/ansible-tmp-1593779716.8926852-80440910949157/AnsiballZ_k8s_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.kubernetes.plugins.modules.k8s_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/var/folders/l3/q6bmclbd53360skfvrqfcbr00000gp/T/ansible_k8s_info_payload_bGc4GK/ansible_k8s_info_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s_info.py\", line 185, in <module>\n  File \"/var/folders/l3/q6bmclbd53360skfvrqfcbr00000gp/T/ansible_k8s_info_payload_bGc4GK/ansible_k8s_info_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s_info.py\", line 181, in main\n  File \"/var/folders/l3/q6bmclbd53360skfvrqfcbr00000gp/T/ansible_k8s_info_payload_bGc4GK/ansible_k8s_info_payload.zip/ansible_collections/community/kubernetes/plugins/modules/k8s_info.py\", line 162, in execute_module\n  File \"/var/folders/l3/q6bmclbd53360skfvrqfcbr00000gp/T/ansible_k8s_info_payload_bGc4GK/ansible_k8s_info_payload.zip/ansible_collections/community/kubernetes/plugins/module_utils/common.py\", line 229, in kubernetes_facts\n  File \"/Users/elopez/Library/Python/2.7/lib/python/site-packages/openshift/dynamic/client.py\", line 94, in get\n    return self.request('get', path, **kwargs)\n  File \"/Users/elopez/Library/Python/2.7/lib/python/site-packages/openshift/dynamic/client.py\", line 44, in inner\n    raise api_exception(e)\nopenshift.dynamic.exceptions.BadRequestError: 400\nReason: Bad Request\nHTTP response headers: HTTPHeaderDict({'Date': 'Fri, 03 Jul 2020 12:35:19 GMT', 'Content-Length': '489', 'Content-Type': 'application/json'})\nHTTP response body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"unable to parse requirement: invalid label value: \\\"\\\\\\\"developer-portal-backend\\\\\\\"\\\": at key: \\\"app\\\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')\",\"reason\":\"BadRequest\",\"code\":400}\n\nOriginal traceback: \n  File \"/Users/elopez/Library/Python/2.7/lib/python/site-packages/openshift/dynamic/client.py\", line 42, in inner\n    resp = func(self, *args, **kwargs)\n\n  File \"/Users/elopez/Library/Python/2.7/lib/python/site-packages/openshift/dynamic/client.py\", line 247, in request\n    _return_http_data_only=params.get('_return_http_data_only', True)\n\n  File \"/Users/elopez/Library/Python/2.7/lib/python/site-packages/kubernetes/client/api_client.py\", line 345, in call_api\n    _preload_content, _request_timeout)\n\n  File \"/Users/elopez/Library/Python/2.7/lib/python/site-packages/kubernetes/client/api_client.py\", line 176, in __call_api\n    _request_timeout=_request_timeout)\n\n  File \"/Users/elopez/Library/Python/2.7/lib/python/site-packages/kubernetes/client/api_client.py\", line 366, in request\n    headers=headers)\n\n  File \"/Users/elopez/Library/Python/2.7/lib/python/site-packages/kubernetes/client/rest.py\", line 241, in GET\n    query_params=query_params)\n\n  File \"/Users/elopez/Library/Python/2.7/lib/python/site-packages/kubernetes/client/rest.py\", line 231, in request\n    raise ApiException(http_resp=r)\n\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP **************************************************************************************************************************************************************
localhost0                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

elopez@MacBook-Pro error_when_using_variable % 
```

```yaml

```

##### EXPECTED RESULTS
populate properly the pod list using the app selector fetched from a variable

##### ACTUAL RESULTS
Seems like somehow is parsing the variable name wrongly, because works properly when hardcoded.

**Comment by Akasurde** [comment]
@ElioLopez-md Can you try 

```yaml
 - name: Get a list of all pods from "{{ application }}" app on "{{ namespace }}" namespace
      k8s_info:
        kind: Pod
        namespace: "{{ namespace }}"
        label_selectors:
              - "app = {{ application }}"
      register: pod_list
```

needs_info

**Comment by ElioLopez-md** [comment]
Thanks @Akasurde, that made the trick.
Regards,

**Comment by Akasurde** [comment]
@ElioLopez-md I updated EXAMPLE section to reflect this example.
